/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pdvsa.h"


void
pdvsa_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char * preguntar_1_arg;
	int  *result_2;
	char * responder_1_arg;
	int  *result_3;
	ticket  validar_1_arg;
	int  *result_4;
	char * pedir_gasolina_1_arg;
	int  *result_5;
	char *pedir_tiempo_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PDVSA_PROG, PDVSA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = preguntar_1(&preguntar_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = responder_1(&responder_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = validar_1(&validar_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = pedir_gasolina_1(&pedir_gasolina_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = pedir_tiempo_1((void*)&pedir_tiempo_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	pdvsa_prog_1 (host);
exit (0);
}
