/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "programa.h"

int *
pedir_gasolina_1_svc(estructura *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * Codigo servidor
	 */
	if (argp->inventario < 38000)
	  result = 0;
	else
	  result = 1;

	return &result;
}

int *
pedir_tiempo_1_svc(estructura *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * Codigo servidor
	 */
	result = argp->tiempo;

	return &result;
}
