/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROGRAMA_H_RPCGEN
#define _PROGRAMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct estructura {
	int tiempo;
	int inventario;
};
typedef struct estructura estructura;

#define CENTROPROG 0x31111111
#define CENTRO_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define pedir_gasolina 1
extern  int * pedir_gasolina_1(estructura *, CLIENT *);
extern  int * pedir_gasolina_1_svc(estructura *, struct svc_req *);
#define pedir_tiempo 2
extern  int * pedir_tiempo_1(estructura *, CLIENT *);
extern  int * pedir_tiempo_1_svc(estructura *, struct svc_req *);
extern int centroprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define pedir_gasolina 1
extern  int * pedir_gasolina_1();
extern  int * pedir_gasolina_1_svc();
#define pedir_tiempo 2
extern  int * pedir_tiempo_1();
extern  int * pedir_tiempo_1_svc();
extern int centroprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_estructura (XDR *, estructura*);

#else /* K&R C */
extern bool_t xdr_estructura ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROGRAMA_H_RPCGEN */
